### PR TITLE
Fix typo in csr_attributes.yaml filename

### PR DESCRIPTION
**Pull request by mdechiaro**
Closes: #68

### CODE REVIEW

**Review by bastelfreak — APPROVED** [review]

**Comment by bastelfreak** [comment]
@mdechiaro thanks for the PR! Can you please sign your commit with gpg or ssh?

**Comment by mdechiaro** [comment]
@bastelfreak I signed this commit, and please take a look, thanks.

**Comment by bastelfreak** [comment]
@mdechiaro the commit has `Signed-off-by: Mark Dechiaro <mdechiaro@users.noreply.github.com>` but it's not signed with your ssh nor gpg key. To check:

```
$ git show e268723dd57be70fbe8f5b99345a83628633cd52 --show-signature
commit e268723dd57be70fbe8f5b99345a83628633cd52 (HEAD -> issue_8, pr1/issue_8)
Author: Mark Dechiaro <mdechiaro@users.noreply.github.com>
Date:   Sat Feb 10 08:04:08 2024 -0600

    Fix typo in filename

    Closes: #68
    Signed-off-by: Mark Dechiaro <mdechiaro@users.noreply.github.com>

diff --git a/puppetserver/docker-entrypoint.d/89-csr_attributes.rb b/puppetserver/docker-entrypoint.d/89-csr_attributes.rb
index 714b3ba..1a5419d 100755
--- a/puppetserver/docker-entrypoint.d/89-csr_attributes.rb
+++ b/puppetserver/docker-entrypoint.d/89-csr_attributes.rb
@@ -5,7 +5,7 @@ require 'yaml'

 begin
   csr_yaml = YAML.dump(JSON.load(ENV['CSR_ATTRIBUTES']))
-  File.open('/etc/puppetlabs/puppet/csr_attrbitues.yaml', 'w') do |file|
+  File.open('/etc/puppetlabs/puppet/csr_attributes.yaml', 'w') do |file|
     file.write(csr_yaml)
   end
 rescue => error
```

vs:

```
$ git show 64cce3363356540aa955335616d14693bcaec9b1 --show-signature
commit 64cce3363356540aa955335616d14693bcaec9b1 (codeowner)
gpg: Signature made Mi 11 Okt 2023 12:42:16 CEST
gpg:                using RSA key C10B6298A584A5632E254DA304D659E6BF1C4CC0
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   3  signed:  10  trust: 0-, 0q, 0n, 0m, 0f, 3u
gpg: Note: third-party key signatures using the SHA1 algorithm are rejected
gpg: (use option "--allow-weak-key-signatures" to override)
gpg: depth: 1  valid:  10  signed:  19  trust: 2-, 0q, 0n, 0m, 8f, 0u
gpg: depth: 2  valid:  17  signed: 151  trust: 17-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2024-04-10
gpg: Good signature from "Tim Meusel <tim.meusel@online-mail.biz>" [ultimate]
gpg:                 aka "Tim Meusel <tim@bastelfreak.de>" [ultimate]
Author: Tim Meusel <tim@bastelfreak.de>
Date:   Wed Oct 11 12:42:16 2023 +0200

    Add CODEOWNERS

diff --git a/.github/CODEOWNERS b/.github/CODEOWNERS
new file mode 100644
index 0000000..61d2843
--- /dev/null
+++ b/.github/CODEOWNERS
@@ -0,0 +1,2 @@
+# No matter which file got changed, request a review from the main developers
+ * @voxpupuli/tools-containerimages
```

**Comment by mdechiaro** [comment]
@bastelfreak thanks for letting me know my ssh key wasn't setup properly for signing. I fixed the issues and appreciate your help.

**Pull request merged**
